### ISSUE TITLE
Default EPA Parameters captured in custom flavor file 

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#28] opened 2018-07-12 13:56 UTC
_From @nandkumarj on February 27, 2018 10:34_

EPA parameters are disabled for  cloudify. However when custom flavor is selected , the default values of EPA parameters is populated in the custom flavor file. So either remove EPA params from custom flavor file or enable EPA Parameters when custom flavor is selected.

_Copied from original issue: vanlittle/VNF-Onboarding#21_

**Comment by amolbjadhav** [comment] 2018-09-12 08:10
We have implemented and tested the code. The issue is fixed and checked in.

**Closed by amolbjadhav** 2018-09-12 08:10 UTC
Labels: bug
