### ISSUE TITLE
Firefox incompatibilities

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#15] opened 2018-07-12 13:50 UTC
_From @vanlittle on May 24, 2018 19:4_

UI Tool not working properly with firefox.    'Continue button does not work on first wizard screen'

How to reproduce the error:
1. login
2. fill out parameters on screen 1 of wizard
3. click continue -> Bug: continue button does nothing

_Copied from original issue: vanlittle/VNF-Onboarding#59_

**Comment by ljilluzzi** [comment] 2018-10-08 13:47
Tested tool on latest firefox, issue with spin button rendering.  Work In-Progress. Remove spin button, replace with drop down. ETA 10/09

**Comment by amolbjadhav** [comment] 2018-10-10 11:08
The issue is fixed. Code is tested and checked in.

**Comment by harshwardhas** [comment] 2018-10-31 08:49
The code is tested with latest Firefox version: 62.0.2 (64 bit).

**Closed** 2018-10-31 08:50 UTC
Labels: P1, bug
