### ISSUE TITLE
Validation for script upload 

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#10] opened 2018-07-12 13:49 UTC
_From @harshwardhas on June 7, 2018 13:9_

If the scripts are uploaded then script name should not be blank

_Copied from original issue: vanlittle/VNF-Onboarding#79_

**Comment by nandkumarj** [comment] 2018-09-12 10:15
Closing this as This is a duplicate of #23.

**Closed by nandkumarj** 2018-09-12 10:15 UTC
Labels: duplicate
