### ISSUE TITLE
Creation of new network for TOSCA - UI Changes - ETA 7/26

### ISSUE THREAD

**Issue by nandkumarj** [vmware/bellhop#32] opened 2018-07-17 08:54 UTC
VNF Onboarding needs to support Creation of new network for TOSCA.
This issues is for tracking UI changes required for the same.

**Comment by amolbjadhav** [comment] 2018-07-26 11:08
The issue is fixed, Code changes are checked in.

**Closed by amolbjadhav** 2018-07-26 11:08 UTC
Labels: In Progress
