### ISSUE TITLE
GUI Issue: NIC definition to EPA configuration

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#25] opened 2018-07-12 13:55 UTC
_From @jambig on March 2, 2018 15:25_

When going from NIC definition (screen 2) to EPA configuration, the overview (on the left side) shows that you are in step 3, but you do not get options for EPA configuration.
See added screenshot for example.
<img width="1175" alt="screen shot 2018-02-27 at 16 21 09" src="https://user-images.githubusercontent.com/36893051/36906446-3994ad32-1e36-11e8-8e4d-825a5708d58b.png">

_Copied from original issue: vanlittle/VNF-Onboarding#29_

**Comment by nandkumarj** [comment] 2018-07-16 12:54
Assinging it to myself for the timebeing. Development effort for Rift has been lagging because of variety of reasons. Will need to look at Rift issues holistically . This issue has been there since the time VNF ONboarding tool was supporting single VDU VNF. I think it will make sense to address Riftware pending issues as and when MultiVDU feature for Rift is taken up.

**Comment by nandkumarj** [comment] 2018-09-12 09:56
This is a duplicate of #37. 
This is implemented and tested, hence closing this issue.

**Closed by nandkumarj** 2018-09-12 09:56 UTC
Labels: bug, duplicate
