### ISSUE TITLE
For VIO + HEAT NIC types only has ‘ normal’ nic type and other supporting NIC types as well 

### ISSUE THREAD

**Issue by amolbjadhav** [vmware/bellhop#44] opened 2018-08-16 12:09 UTC
As discussed in Look and Feel Demo on 13th August 2018,  The additional NICs type supported in  VIO + HEAT should be added

**Comment by nandkumarj** [comment] 2018-08-21 04:57
This is a duplicate of #42

**Comment by nandkumarj** [comment] 2018-09-12 09:31
This is being tracked under issue #42. So closing this as duplicate.

**Closed** 2018-09-12 09:34 UTC
Labels: duplicate
