### ISSUE TITLE
Validation of newly added parameters for network creation in Cloudify and HEAT Orchestrator

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#1] opened 2018-07-11 21:19 UTC
_From @amolbjadhav on July 11, 2018 9:11_

_Copied from original issue: vanlittle/VNF-Onboarding#91_

**Comment by nandkumarj** [comment] 2018-07-16 14:48
There are around 8 parameters newly added to VNF Onboarding UI . Validation for which will be addressed under this issue.

**Comment by amolbjadhav** [comment] 2018-09-24 11:03
The issue is Fixed.  All these parameters are mandatory. we have checked in the code.

**Closed by amolbjadhav** 2018-09-24 11:03 UTC
Labels: enhancement
