### ISSUE TITLE
Validation for email delivery 

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#11] opened 2018-07-12 13:49 UTC
_From @harshwardhas on June 7, 2018 13:8_

 If the email is not delivered, the sign up should be successful with warning message.

_Copied from original issue: vanlittle/VNF-Onboarding#78_

**Comment by nandkumarj** [comment] 2018-09-24 09:31
This is a duplicate of #14 . So closing this one.

**Closed by nandkumarj** 2018-09-24 09:31 UTC
Labels: duplicate, help wanted
