### ISSUE TITLE
When we traverse back and forth in GUI, the old values gets retained in summary page.

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#9] opened 2018-07-12 13:48 UTC
_From @amolbjadhav on June 13, 2018 6:12_

Steps to reproduce:
1. Select Vim and Orchestrator  combination 
2. Select additional networks e..g 5 and add the details in "Network Configurations"
3. Add other details and proceed till the summary page.
4. Traverse back and change the Additional networks to some less numbers e.g. 2  or 
Reduce the the Number of NICs for VM in Network Configuration page.
4. Traverse forth to summary page, the old values filled previously would get retained and would reflect in blueprint as well.

This is known limitation due to present code architecture and would need modifications in the static structures which are storing these values.

_Copied from original issue: vanlittle/VNF-Onboarding#80_

**Comment by nandkumarj** [comment] 2018-07-16 13:49
This is a day one issue. This bug is due to inherent limitations of frontend datastructures. This issue exhibits itself only in case where during Blueprint workflow, user goes back from current page and changes some of the inputs. However this is not high priority as there would be very few use cases where user would go back to change something.

**Comment by harshwardhas** [comment] 2018-10-18 11:17
Issue is resolved and tested.  code checked in

**Comment by amolbjadhav** [comment] 2018-10-31 08:51
The issue is fixed. Code is tested and checked in.

**Closed by amolbjadhav** 2018-10-31 08:51 UTC
Labels: P1, bug
